runtime: python310
entrypoint: gunicorn -b :$PORT server:app

env_variables:
  WEATHER_API_KEY: ""
  FIREBASE_URL: ""
  WEATHER_API_URL: ""

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65

instance_class: F2

